### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by Treverr** [parse-community/parse-dashboard#1049]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
npm install -g parse-dashboard
sudo parse-dashboard --config /Users/Trever/parsedash.json --allowInsecureHTTP=1

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

```
> parse-dashboard@1.1.2 dev /usr/local/lib/node_modules/parse-dashboard
> node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch

module.js:557
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/parse-dashboard/webpack/build.config.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/parse-dashboard/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/parse-dashboard/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parse-dashboard@1.1.2 dev: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-dashboard@1.1.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trever/.npm/_logs/2019-04-04T05_16_05_965Z-debug.log
Trevers-Server:parse-dashboard trever$ Iconsfolder at path: /usr/local/lib/node_modules/parse-dashboard/Parse-Dashboard/icons not found!
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:4040
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1523:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by Treverr** [comment]
I installed with npm and still am getting this error and I cannot figure out why

**Comment by dplewis** [comment]
> Error: listen EADDRINUSE 0.0.0.0:4040

Looks like you already have a dashboard running. You have to kill that process.

`$ ps aux | grep node`
`$ kill -9 {processId}`

**Comment by dplewis** [comment]
There is a PR. Opened for this should be included in the next release

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/1070
