### ISSUE TITLE
Issue with logs pages - t.match is not a function

### ISSUE THREAD

**Issue by macarthuror** [parse-community/parse-dashboard#1459]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Running Locally
```
parse-dashboard: 2.0.5
parse-server: 3.10.0
express: 4.17.1
```

#### Steps to reproduce

Similar to #1112 
Open up dashboard and navigate to logs page
Sometimes works but mostly of the time it crash

#### Logs/Trace

```javascript
Uncaught (in promise) TypeError: t.match is not a function
    at Yf (dashboard.bundle.js:95)
    at oa (dashboard.bundle.js:45)
    at eu (dashboard.bundle.js:45)
    at xu (dashboard.bundle.js:45)
    at yu (dashboard.bundle.js:45)
    at su (dashboard.bundle.js:45)
    at dashboard.bundle.js:45
    at t.unstable_runWithPriority (dashboard.bundle.js:53)
    at qi (dashboard.bundle.js:45)
    at Gi (dashboard.bundle.js:45)
```

**Comment by davehibshman** [comment]
Having same problem running on local Ubuntu 20.04 box:
parse-dashboard: 2.10.0
parse-server: 4.2.0
express: 4.17.1

**Comment by FELS-Zak** [comment]
I've never had any logs - 
How do you build this dashboard once you make a change ?

**Comment by Mabenan** [comment]
I think i have found the  problem for me the following line made the problem:
`{"message":{"ok":0,"code":40352,"codeName":"Location40352","name":"MongoError"},"code":1,"level":"error","stack":"Error: MongoError: FieldPath cannot be constructed with empty string\n    at C:\\Users\\doene\\Documents\\ServerManagerDocker\\node_modules\\parse-server\\lib\\Controllers\\DatabaseController.js:1170:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-08-20T09:59:24.974Z"}`

The problem was solved when i changed the message property to a string like that:
`{"message":"MongoError","code":1,"level":"error","stack":"Error: MongoError: FieldPath cannot be constructed with empty string\n    at C:\\Users\\doene\\Documents\\ServerManagerDocker\\node_modules\\parse-server\\lib\\Controllers\\DatabaseController.js:1170:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-08-20T09:59:24.974Z"}`

So my assumption here is that the message property is expected to be an string. Which it isn't for errors thrown by Mongo

**Comment by Mabenan** [comment]
after looking at the source i think it would be the easiest thing to check the message property and if it is not a string to execute a stringify maybe `JSON.stringify`.

**Comment by mtrezza** [comment]
Can you verify whether this issue still exists with the current master branch?

**Comment by Mabenan** [comment]
Yes it does

**Comment by mtrezza** [comment]
@Mabenan Thanks for confirming. The next step would be to determine whether this should be fixed in Parse Server (where the log is written) or in dashboard (where the log is displayed).

If the expectation also from Parse Server side is that `message` is a string, not an object, then it would be enough to `JSON.stringify` the `message` value before writing it to the log.

**Comment by youwhoyou** [comment]
still not fixed

**Comment by mtrezza** [comment]
As [explained](https://github.com/parse-community/parse-dashboard/issues/1459#issuecomment-908583906) above, these 2 issues:
- Parse Dashboard: fail gracefully if log cannot be parsed
- Parse Server: log `message` must always be a string, not an object

Anyone who wants to pick up any of these 2 issues, please go ahead.
