### ISSUE TITLE
Access to Push > Create an audience returns 404

### ISSUE THREAD

**Issue by pdsolutions** [parse-community/parse-dashboard#2626]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Unable to Create an audience in Push
Please note that it fails on  parse-dashboard": 6.0.0 on dokku and parse-dashboard@6.0.0-alpha.19 on local fresh installation.

### Steps to reproduce

In order to reproduce please login -> Push -> Create an audience

On parse dashboard 5.3.0 with "parse-server": "^5.6.0" it's working, please see the latest attached image.

UPDATE: 
I've installed parse dashboard 5.4.0 on local, configured parse-dashboard-config.json with both apps, one on a parse server 7.3.0 and another on 5.6.0 and it works, so the problem is parse dashboard 6.0.0

### Actual Outcome

Blank page, no popup

### Expected Outcome

Create an audience popup

### Environment
Dokku package.json:

  "dependencies": {
    "@parse/fs-files-adapter": "^3.0.0",
    "@parse/s3-files-adapter": "^3.0.0",
    "@parse/simple-mailgun-adapter": "^2.0.0",
    "aws-sdk": "^2.1691.0",
    "axios": "^1.7.7",
    "cookie-parser": "^1.4.7",
    "cookie-session": "^2.1.0",
    "dotenv": "^16.4.5",
    "ejs": "^3.1.10",
    "express": "^4.21.1",
    "express-ejs-layouts": "^2.5.1",
    "i18n": "^0.15.1",
    "limax": "^4.1.0",
    "mailgen": "^2.0.28",
    "mailgun.js": "^10.2.3",
    "method-override": "^3.0.0",
    "moment": "^2.30.1",
    "node-cron": "^3.0.3",
    "parse": "^5.3.0",
    "parse-dashboard": "^6.0.0",
    "parse-server": "^7.3.0",
    "parse-server-mailgun-adapter-template": "^1.1.7",
    "pm2": "^5.4.2",
    "sharp": "^0.33.5",
    "stripe": "^17.3.0",
    "winston": "^3.15.0"
  }
  ...

Local package.json -> see on https://github.com/parse-community/parse-dashboard/

parse-dashboard-config.json:
{
  "apps": [
    {
      "serverURL": "https://domain/api",
      "appId": "myAppId",
      "masterKey": "example",
      "appName": "example",
      "iconName": "",
      "primaryBackgroundColor": "#003a87",
      "secondaryBackgroundColor": "#0067f0"
    }
  ],
  "iconsFolder": "icons"
}

Dashboard
- Parse Dashboard version: 6.0.0
- Browser (Safari, Chrome, Firefox, Edge, etc.): Chrome 
- Browser version:  130.0.6723.91 (Build oficial) (arm64)

Server
- Parse Server version: 7.3.0
- Operating system: Ubuntu with Dokker 24.0.7
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Custom VPS with Dokker 24.0.7

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 8.0.1
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): remote, same server same dokku

### Logs
There are no significant logs in the dokku logs <app_name>
Blank page with err in Chrome console: 

dashboard.bundle.js:2 TypeError: Cannot read properties of undefined (reading 'undefined')
    at Object.m (dashboard.bundle.js:2:933407)
    at Gp (dashboard.bundle.js:2:3006032)
    at Jo (dashboard.bundle.js:2:1952946)
    at Es (dashboard.bundle.js:2:1998904)
    at kl (dashboard.bundle.js:2:1991688)
    at xl (dashboard.bundle.js:2:1991613)
    at fl (dashboard.bundle.js:2:1988646)
    at dashboard.bundle.js:2:1940360
    at t.unstable_runWithPriority (dashboard.bundle.js:2:2182421)
    at Ki (dashboard.bundle.js:2:1940069)

<img width="723" alt="Captura de pantalla 2024-11-01 a las 11 54 06" src="https://github.com/user-attachments/assets/b7e22438-2a9a-4d39-b603-cb5c005c6a75">
<img width="723" alt="Captura de pantalla 2024-11-01 a las 11 54 39" src="https://github.com/user-attachments/assets/896e4a06-2f95-4a75-8ad4-a91a67503cc7">
<img width="1572" alt="Captura de pantalla 2024-11-01 a las 11 55 14" src="https://github.com/user-attachments/assets/9c4361e4-fe05-4b75-a479-f9fd0c70d48c">
<img width="1364" alt="Captura de pantalla 2024-11-01 a las 12 33 06" src="https://github.com/user-attachments/assets/b9f05b8c-eba9-4e14-93cc-795df5bdf6e2">

**Comment by KloWhrhyde** [comment]
Do we have an update on this issue ?

**Comment by R3D347HR4Y** [comment]
Had this issue too in latest versions of Parse Dashboard, it prevents me from updating to anything after 5.4.0 and I really want to use infopanels which were released in 6.0.0...
If anyone found the problem that would be great to fix

**Comment by R3D347HR4Y** [comment]
Bump, this is a very bothersome issue, on all versions after 6.0.0 creating an Audience does not work, it's not dependent on Parse server version or environnment

**Comment by hiennguyen92** [comment]
I have the same issue. when I click on "Create an audience" it doesn't even show the dialog, just shows a blank page.

**Comment by mtrezza** [comment]
Please try out https://github.com/parse-community/parse-dashboard/pull/2983 whether it fixes the issue
