### ISSUE TITLE
Local parse master key error -- Key is set appropriately. 

### ISSUE THREAD

**Issue by tailord** [parse-community/parse-dashboard#638]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

#### Environment Setup
Server
parse-server version (Be specific! Don't say 'latest'.) :
Operating System: OSX 10.10.5
Hardware: macbook air 1.6 GHz Intel Core i5 4 GB 1600 MHz DDR3
Localhost or remote server? localhost
Database
MongoDB version: version: 3.0.13 (MMAPv1)
Storage engine: mlab
Hardware: aws
Localhost or remote server? mlab

#### Steps to reproduce
Execute command on local build in simulator. 

Master key is set appropriately in index.js on parse server example running on local machine. 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

error: Error generating response. { Error: unauthorized: master key is required
    at promiseEnforceMasterKeyAccess (/Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/middlewares.js:297:17)
    at /Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/PromiseRouter.js:132:22
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) status: 403, message: 'unauthorized: master key is required' } status=403, message=unauthorized: master key is required

and 

error: Error generating response. TypeError: mailgun.sendEmail is not a function
    at /Users/alexgriswold/parse-server-example/cloud/main.js:6:11
    at _ret.v (/Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/Routers/FunctionsRouter.js:203:15)
    at /Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/Routers/FunctionsRouter.js:171:16
    at handleCloudFunction (/Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/Routers/FunctionsRouter.js:206:10)
    at /Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/PromiseRouter.js:253:9
    at /Users/alexgriswold/parse-server-example/node_modules/parse-server/lib/PromiseRouter.js:289:9
    at Layer.handle [as handle_request] (/Users/alexgriswold/parse-server-example/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/alexgriswold/parse-server-example/node_modules/parse-server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/alexgriswold/parse-server-example/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/alexgriswold/parse-server-example/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)

**Comment by JacobJT** [comment]
Sounds like you're not passing {useMasterKey:true} into the options of a parse function. Parse Hosted Cloud used implicit permissions, meaning the user's session tokens were passed into every parse function (queries, fetches, saves, etc.), and you could call `Parse.Cloud.useMasterKey()` to implicitly pass the master key to all proceeding functions.

Now, you need to pass these options explicitly to all the parse functions.  User sessions are part of the request to cloud functions, and the master key can be passed as needed, but `Parse.Cloud.useMasterKey()` is deprecated and no longer does anything.

**Comment by JacobJT** [comment]
Also, the mailgun module is not natively included. It was one of the few that Parse included by default, but you need to add it to your package.json and do an `npm install` to include it on your server.

**Comment by tailord** [comment]
Thanks, can you please help me identify where in the function to pass the {useMasterKey:true}? I have been going in circles for the last 10-15 hours here. 

//email cloud code
var mailgun = require("mailgun");

mailgun.initialize("tailxxxx.com", "key-3xxxxxxx");
Parse.Cloud.define("sendEmail", function(request, response) {
  mailgun.sendEmail({
    to: request.params.to,
    from: " Tailor'd <xxxx>",
    subject: request.params.subject,
    text: request.params.text
  }, {
    success: function(httpResponse) { response.success("Email sent!"); },
    error: function(httpResponse) { response.error("Error: " + request.params + " to: " + request.params.to + " subject: " + request.params.subject + " text: " + request.params.text); }
  });
});
