### ISSUE TITLE
events.js:160       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by ravkushw** [parse-community/parse-dashboard#767]
C:\Users\rasingh>webdriver-manager update
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)

**Comment by ravkushw** [comment]
This is  happening when am trying to Installing and Starting the Server, after Protractor installation is done successfully.
