### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by lebeier** [parse-community/parse-dashboard#791]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

After npm install -g parse-dashboard, I have tried to trigger the command and got the following error.

/usr/lib/node_modules/parse-dashboard/Parse-Dashboard/app.js:80
        apps: [...config.apps], // make a copy
               ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/parse-dashboard/Parse-Dashboard/index.js:13:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Am I missing something?

**Comment by lebeier** [comment]
upgraded node and its resolved.

**Comment by montymxb** [comment]
@lebeier did you manage to resolve this?

**Comment by flovilmart** [comment]
The splat operator being removed, it should all be fine now
