### ISSUE TITLE
react app not executing with create-react-app package

### ISSUE THREAD

**Issue by ruchikam** [parse-community/parse-dashboard#837]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/ajay/Desktop/newReactMapApp/my-app1/public ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at createFsWatchInstance (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/ajay/Desktop/newReactMapApp/my-app1/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app1@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app1@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ajay/.npm/_logs/2018-02-07T11_30_21_040Z-debug.log

**Comment by flovilmart** [comment]
Hi, hi believe this is not related to this project, please reopen the issue with additional information of needed
