### ISSUE TITLE
events.js:183       throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Anindo94** [parse-community/parse-dashboard#842]
[17:06:39]  lint finished in 10.03 s
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:\Program Files\nodejs\node.exe" ENOENT
    at notFoundError (C:\Users\bizruntime\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\bizruntime\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\bizruntime\AppData\Roaming\npm\node_modules\ionic\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
PS E:\Ionic\demoudemy\exercise>

This is coming when i am using ionic serve to run the code Please help and also nothing else is running in the same port I have only one application running in this port number.

**Comment by flovilmart** [comment]
I’m not sure why you’te Using ionic with parse dashboard as it’s a react based project and self fontaine web app + server. Please reopen with more information about your setup and installation.

**Comment by TheFutureJholler** [comment]
i am trying to run gulp local command in my terminal, can't get what's wrong... please help!

Aristotle:source iram$ gulp local
[12:40:16] Using gulpfile ~/projects/TestSCA/source/gulpfile.js
[12:40:16] Starting 'local'...
[12:40:16] Starting 'local-install'...
[12:40:16] Finished 'local-install' after 112 μs
...
...
...
+--------------------------------------------------------------+
+- Local http server available at: http://localhost:7777/
+- Watching current folder: /Users/iram/projects/TestSCA/source/Modules
+- To cancel Gulp Watch enter: control + c
+--------------------------------------------------------------+
events.js:183
throw er; // Unhandled 'error' event
^

Error: listen EADDRINUSE 0.0.0.0:7777
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at Server.setupListenHandle [as _listen2] (net.js:1367:14)
at listenInCluster (net.js:1408:12)
at doListen (net.js:1517:7)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
Aristotle:source iram$

**Comment by nazzal88** [comment]
Same Error

**Comment by nazzal88** [comment]
@Anindo94  Any Solution?

**Comment by bcopmt143** [comment]
Can you try by changing listing port? it works for me!

**Comment by halitguvenilir** [comment]
@bcopmt143 Thanks idea ;)

**Comment by therealsujitk** [comment]
> Can you try by changing listening port? it works for me!

@bcopmt143 Yes! This worked like a charm... tho i'm curious to why there was this error in the first place :thinking:
