### ISSUE TITLE
events.js:188 - throw err;

### ISSUE THREAD

**Issue by TH3RMIT3** [parse-community/parse-dashboard#846]
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. ([object Object])
    at Client.emit (events.js:186:19)
    at WebSocketConnection.onError (C:\Users\Owain\Desktop\JSBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:371:17)
    at WebSocket.onError (C:\Users\Owain\Desktop\JSBot\node_modules\ws\lib\event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at _receiver.cleanup (C:\Users\Owain\Desktop\JSBot\node_modules\ws\lib\websocket.js:211:14)
    at Receiver.cleanup (C:\Users\Owain\Desktop\JSBot\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (C:\Users\Owain\Desktop\JSBot\node_modules\ws\lib\websocket.js:206:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\Owain\Desktop\JSBot>pause
Press any key to continue . . .

Hi, I have this issue which only appears after I have left the code running overnight. I was wondering if anyone would be able to help me understand this, and possible find a solution.

**Comment by Resistiv** [comment]
Hi TH3RMIT3! I happen to be having the same problem with my Discord bot. After further research, I have found that this may be due to Internet timeouts or a connection error. I myself haven't found a solution, but I hope this helps!

**Comment by Anthamation** [comment]
I've got the same problem. I was hoping that there would be an option to reconnect the bot after the error event.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Once you aren't changing the program of the bot, you could use forever [(here)](https://github.com/foreverjs/forever) so that your program will restart as soon as it crashes. If you are changing files often, you can use the parameter -w or --watch to restart on file changes (like nodemon).
