### ISSUE TITLE
Send New Push and adding audience not working

### ISSUE THREAD

**Issue by JacobJT** [parse-community/parse-dashboard#853]
Sorry if this is not clear, I wrote this out as I was experiencing it. Will answer any clarification questions I can.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=1.0.23 of Parse Dashboard. (1.2.0)

- [x ] You're running version >=2.3.2 of Parse Server. (2.7.4)

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
mLab, AWS or local host on a 2015 MBP High Sierra

#### Steps to reproduce
I had 0 Audiences. I was on Parse-Dashboard 1.1.2 and found I couldn't open the push tab, so upgraded to 1.2.0.  

When going to the push tab, the page would mostly load, but still had a loading indicator and [LOGA] would appear in my server logs.  I noted that it was only the Send New Push option from the side bar that had this issue. The Audiences tab worked, and the Past Pushes tab worked fine.  

However, I did not have any Audiences - I thought this was perhaps causing the errors / hang. So I tried to add an audience. Just select OS X, Gave it the name`OS X (should be no one)`, and tried to create it by pressing "Use this audience". Nothing appeared to happen, so I pressed "Use this audience" again, and [LOGB] appeared in my server.  I went back through and noticed before [LOGB] I did have a log showing the first press appeared to have worked on the server and returned an objectId for an Audience object I think, despite parse-dashboard not responding. Unfortunately, I cleared this log before I could copy it.

I pressed cancel, and Send New Push still hangs, and Audiences shows no results, and my logs show [LOGC].

As a side note, it appears to load my Schemes with every load of any of these pages - is that necessary?

#### Logs/Trace
LOGA:
```
error: Error generating response. SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response.results.forEach.item (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:37:27)
    at Array.forEach (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:36:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) 
error: Uncaught internal server error. SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response.results.forEach.item (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:37:27)
    at Array.forEach (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:36:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response.results.forEach.item (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:37:27)
    at Array.forEach (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:36:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response.results.forEach.item (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:37:27)
    at Array.forEach (native)
    at _ClassesRouter2.default.handleFind._rest2.default.find.then.response (MY_PATH/node_modules/parse-server/lib/Routers/AudiencesRouter.js:36:24)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

LOGB:
```
error: Error generating response. ParseError {
  code: 137,
  message: 'A duplicate value for a field with unique values was provided',
  underlyingError: 
   { MongoError: E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }
       at Function.MongoError.create (MY_PATH/node_modules/parse-server/node_modules/mongodb-core/lib/error.js:45:10)
       at toError (MY_PATH/node_modules/parse-server/node_modules/mongodb/lib/utils.js:149:22)
       at MY_PATH/node_modules/parse-server/node_modules/mongodb/lib/collection.js:696:39
       at handler (MY_PATH/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/replset.js:1210:22)
       at MY_PATH/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:541:18
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
     name: 'MongoError',
     message: 'E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }',
     driver: true,
     index: 0,
     code: 11000,
     errmsg: 'E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }' },
  userInfo: { duplicated_field: 'name' } } code=137, message=A duplicate value for a field with unique values was provided, name=MongoError, message=E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }, driver=true, index=0, code=11000, errmsg=E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }, duplicated_field=name
error: A duplicate value for a field with unique values was provided code=137, message=A duplicate value for a field with unique values was provided, name=MongoError, message=E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }, driver=true, index=0, code=11000, errmsg=E11000 duplicate key error index: MY_DB._Audience.$name_1 dup key: { : "OS X (should be no one)" }, duplicated_field=name
```

LOGC:
```
error: Error generating response. ParseError {
  code: 102,
  message: 'Invalid parameter for query: audience_limit' } code=102, message=Invalid parameter for query: audience_limit
error: Invalid parameter for query: audience_limit code=102, message=Invalid parameter for query: audience_limit
```

**Comment by JacobJT** [comment]
Someone in the thread on parse-server pointed out I may have an Audience object in the _Audience collection on my database. Turns out they were right, I have a really old one from 2016. I'm not 100% sure, but believe this was creating while still using Parse.com but self hosting the database on mLab. 

Since I clearly don't use this feature it's not a priority for me, but figured this should be known. 

Here's the offending _Audience object

```
{
    "_id": "<redacted>",
    "_created_at": {
        "$date": "2016-07-30T03:05:01.542Z"
    },
    "_updated_at": {
        "$date": "2016-07-30T03:05:01.542Z"
    },
    "query": {
        "channels": {
            "$in": [
                "testPush"
            ]
        },
        "deviceType": {
            "$in": [
                "ios"
            ]
        }
    },
    "name": "testPush",
    "times_used": 8,
    "_last_used": {
        "$date": "2016-08-02T17:10:24.519Z"
    }
}
```

**Comment by BillyJohn3** [comment]
Hi there, I have the same problem but don't have any old audience objects at all as this is a completely new server and database.
Is there a fix for this Parse Error 102?
Thanks

**Comment by JacobJT** [comment]
@BillyJohn3 Have you checked your database collection directly to ensure the _Audience collection has no records?

**Comment by mtrezza** [comment]
Closing as this issue seems to have been resolved; this only seems to occur with legacy `Audience` objects in the DB from old Parse Server versions (~2016).
