### ISSUE TITLE
events.js:183 Error in react native

### ISSUE THREAD

**Issue by waleed6161** [parse-community/parse-dashboard#872]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! last@0.1.0 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the last@0.1.0 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wleed\AppData\Roaming\npm-cache\_logs\2018-08-02T04_43_40_201Z-debug.log
i am stuck here ..  `

**Comment by flovilmart** [comment]
Unrelated with this project
